### PR TITLE
utsushi: Fix build with sane-backends > 1.0.x

### LINKED ISSUE #3791: FTBFS: utsushi
```
  CXXLD    verify
make[3]: Leaving directory '/home/build/YPKG/root/utsushi/build/imagescan-3.65.0/drivers/esci'
Making all in tests
make[3]: Entering directory '/home/build/YPKG/root/utsushi/build/imagescan-3.65.0/drivers/esci/tests'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/build/YPKG/root/utsushi/build/imagescan-3.65.0/drivers/esci/tests'
make[2]: Leaving directory '/home/build/YPKG/root/utsushi/build/imagescan-3.65.0/drivers/esci'
Making all in sane
make[2]: Entering directory '/home/build/YPKG/root/utsushi/build/imagescan-3.65.0/sane'
Making all in .
make[3]: Entering directory '/home/build/YPKG/root/utsushi/build/imagescan-3.65.0/sane'
  CXX      backend.lo
In file included from backend.cpp:56:
version.hpp:41:2: error: #error "SANE installation violates versioning portability constraints."
   41 | #error "SANE installation violates versioning portability constraints."
      |  ^~~~~
```

Package is archived upstream so a deprecation may be suitable. `libboost` rebuilds are blocked on this package.

### PR DESCRIPTION
**Pull request by Staudey**
**Summary**

Resolves #3791

**Test Plan**
- Lauched the app and clicked some buttons (I don't have a scanner to test)

**Checklist**

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by joebonrichie** [comment]
thz bbz :heart:

**Review by joebonrichie — APPROVED** [review]
